# -*- coding: utf-8 -*-
"""iot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/124KMr2VU3KnFXWcI58yz7SSNWMFaOobN
"""

import streamlit as st
import pickle
import numpy as np
import pandas as pd
import base64
import urllib.request
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import os

st.set_page_config(page_title="🩺 Diabetes Prediction", layout="wide")

# 🔹 Background image setup from raw GitHub URL
image_url = "https://raw.githubusercontent.com/harishmani7846/regress/main/WhatsApp%20Image%20.jpg"

def add_bg_from_url(url):
    response = urllib.request.urlopen(url)
    encoded = base64.b64encode(response.read()).decode()
    st.markdown(
         f"""
         <style>
         .stApp {{
             background-image: url("data:image/jpg;base64,{encoded}");
             background-size: cover;
             background-attachment: fixed;
         }}
         </style>
         """,
         unsafe_allow_html=True
     )

add_bg_from_url(image_url)

# 🔊 Tamil song from GitHub raw link
st.markdown(
    """
    <audio controls autoplay loop>
        <source src="https://raw.githubusercontent.com/harishmani7846/regress/main/Unkoodave%20Porakkanum(KoshalWorld.Com).mp3" type="audio/mpeg">
        Your browser does not support the audio element.
    </audio>
    """,
    unsafe_allow_html=True
)

# 🔹 App Title
st.title("🩺 Diabetes Prediction using Logistic Regression")

# 🧪 Sample Dataset
data = {
    'age': [50, 31, 32, 45, 29],
    'plas': [148, 85, 89, 120, 94],
    'insu': [0, 0, 94, 0, 168],
    'mass': [33.6, 26.6, 28.1, 35.3, 23.1],
    'class': [1, 0, 0, 1, 0]
}
df = pd.DataFrame(data)

# 🔹 Train model
X = df[['age', 'plas', 'insu', 'mass']]
y = df['class']
model = LogisticRegression()
model.fit(X, y)

# 📝 Input Fields
st.subheader("👤 Enter Patient Data")
age = st.number_input("Age", min_value=1, max_value=120, value=30)
plas = st.number_input("Plasma Glucose", min_value=0, max_value=200, value=100)
insu = st.number_input("Insulin", min_value=0, max_value=1000, value=100)
mass = st.number_input("BMI", min_value=10.0, max_value=80.0, value=25.0)

# 🔮 Prediction
if st.button("Predict"):
    input_data = np.array([[age, plas, insu, mass]])
    pred = model.predict(input_data)
    if pred[0] == 1:
        st.success("🎯 Prediction: Diabetic")
    else:
        st.success("💪 Prediction: Not Diabetic")

# 📈 Model Accuracy
st.subheader("✅ Model Accuracy")
train_pred = model.predict(X)
acc = accuracy_score(y, train_pred)
st.write(f"Training Accuracy: {acc:.2f}")

pip install streamlit
